---
- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Install oh-my-zsh for users with zsh shell
  become: yes
  become_user: "{{ item.name }}"
  command: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  loop: "{{ users }}"
  when: item.shell == '/bin/zsh'