---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure nginx vhost
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/default
  notify: Restart nginx