---
- hosts: container
  become: yes
  vars_files:
    - vars/users.yml
    - vars/packages.yml
  roles:
    - create_users
    - install_zsh
    - configure_ssh
    - install_packages
    - install_nginx
    - deploy_static

    